import type { Metadata } from "next";
import Head from 'next/head';
import { Inter } from 'next/font/google'
import "./globals.css";

const inter_init = Inter({
  subsets:['latin'],
  weight:['100','400','300','500','700'],
  variable:'--font-inter'

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter_init.variable}>{children}</body>
    </html>
  );
}
